"""Build PDF audit documents from :class:`~proxy.reporting.types.AuditReportBundle`."""

from __future__ import annotations

import importlib.metadata
import io
from datetime import date
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Sequence

    from fpdf import FPDF

    from proxy.reporting.types import AuditReportBundle


def _package_version() -> str:
    """Return installed ``overage`` version or a placeholder."""
    try:
        return importlib.metadata.version("overage")
    except importlib.metadata.PackageNotFoundError:
        return "0.0.0"


def _timeseries_chart_png(bundle: AuditReportBundle) -> bytes | None:
    """PNG bytes for reported vs estimated daily tokens, or None if not enough points."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.dates as mdates
    import matplotlib.pyplot as plt

    pts = bundle.timeseries
    if len(pts) < 2:
        return None

    xs: list[date] = [date.fromisoformat(str(p.date)[:10]) for p in pts]
    xnum = mdates.date2num(xs)

    fig, ax = plt.subplots(figsize=(7.5, 2.8), dpi=120)
    reported = [p.reported_reasoning_tokens for p in pts]
    estimated = [p.estimated_reasoning_tokens for p in pts]
    ax.plot(xnum, reported, label="Reported", color="#c62828", linewidth=1.8)
    ax.plot(xnum, estimated, label="Estimated", color="#0277bd", linewidth=1.8)
    ax.set_ylabel("Reasoning tokens")
    ax.set_title("Daily reasoning tokens (reported vs Overage estimate)")
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m-%d"))
    fig.autofmt_xdate()
    ax.legend(loc="upper right", fontsize=8)
    ax.grid(True, alpha=0.25)
    fig.tight_layout()
    buf = io.BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight", facecolor="white")
    plt.close(fig)
    return buf.getvalue()


def _section_heading(pdf: FPDF, title: str) -> None:
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 7, title, ln=1)
    pdf.set_font("Helvetica", "", 10)


def _paragraph(pdf: FPDF, text: str) -> None:
    pdf.multi_cell(0, 5, text)
    pdf.ln(1)


def _table_row(
    pdf: FPDF,
    cells: list[str],
    widths: Sequence[float],
    bold: bool = False,
) -> None:
    pdf.set_font("Helvetica", "B" if bold else "", 8)
    for txt, w in zip(cells, widths, strict=True):
        pdf.cell(w, 6, txt[:48], border=1, align="L")
    pdf.ln()


def _write_cover(pdf: FPDF, bundle: AuditReportBundle) -> None:
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "Overage audit report", ln=1)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(70, 70, 70)
    pdf.cell(0, 5, "Independent audit layer for LLM reasoning token billing", ln=1)
    pdf.set_text_color(0, 0, 0)
    period = f"{bundle.period_start} to {bundle.period_end}"
    pdf.cell(0, 5, f"Account: {bundle.user_label}   |   Period: {period}", ln=1)
    pdf.cell(0, 5, f"Report generated by Overage v{_package_version()}", ln=1)
    pdf.ln(3)


def _write_executive_and_methodology(pdf: FPDF, bundle: AuditReportBundle) -> None:
    o = bundle.overall
    _section_heading(pdf, "Executive summary")
    _paragraph(
        pdf,
        f"This report covers {o.total_calls:,} audited API calls in the selected period. "
        f"Providers reported {o.total_reported_reasoning_tokens:,} reasoning tokens versus "
        f"{o.total_estimated_reasoning_tokens:,} tokens estimated by Overage (PALACE ML plus "
        f"latency-based checks). Aggregate discrepancy is {o.aggregate_discrepancy_pct:+.2f}% "
        f"with an estimated dollar impact of ${o.total_dollar_impact:,.2f}. "
        f"The honoring rate (reported tokens falling within the PALACE confidence interval) "
        f"is {o.honoring_rate_pct:.1f}%.",
    )

    _section_heading(pdf, "Methodology")
    _paragraph(
        pdf,
        "Overage proxies LLM traffic, records provider usage payloads, and runs asynchronous "
        "estimation: a fine-tuned PALACE model predicts reasoning-token ranges, and a timing "
        "regression provides a second signal. Combined estimates and provider-reported counts "
        "yield discrepancy percentages and dollar impact using published per-model pricing "
        "assumptions maintained in the Overage configuration.",
    )
    _paragraph(
        pdf,
        "Confidence intervals: PALACE emits low/high bounds per call; the honoring rate counts "
        "calls where reported reasoning tokens lie inside that interval.",
    )


def _write_provider_model_tables(pdf: FPDF, bundle: AuditReportBundle) -> None:
    _section_heading(pdf, "Per-provider summary")
    w_prov = [42.0, 22.0, 28.0, 28.0, 28.0, 22.0]
    _table_row(
        pdf,
        ["Provider", "Calls", "Reported", "Estimated", "Disc %", "$ impact"],
        w_prov,
        bold=True,
    )
    pdf.set_font("Helvetica", "", 8)
    for g in bundle.by_provider:
        _table_row(
            pdf,
            [
                g.group_key,
                str(g.call_count),
                str(g.total_reported_reasoning_tokens),
                str(g.total_estimated_reasoning_tokens),
                f"{g.aggregate_discrepancy_pct:+.1f}",
                f"{g.total_dollar_impact:.2f}",
            ],
            w_prov,
        )
    pdf.ln(2)

    _section_heading(pdf, "Per-model summary")
    w_model = [52.0, 22.0, 26.0, 26.0, 26.0, 20.0]
    _table_row(
        pdf,
        ["Model", "Calls", "Reported", "Estimated", "Disc %", "$ impact"],
        w_model,
        bold=True,
    )
    for g in bundle.by_model:
        _table_row(
            pdf,
            [
                g.group_key[:32],
                str(g.call_count),
                str(g.total_reported_reasoning_tokens),
                str(g.total_estimated_reasoning_tokens),
                f"{g.aggregate_discrepancy_pct:+.1f}",
                f"{g.total_dollar_impact:.2f}",
            ],
            w_model,
        )
    pdf.ln(2)


def _write_top_calls_section(pdf: FPDF, bundle: AuditReportBundle) -> None:
    _section_heading(pdf, "Top calls by absolute discrepancy")
    w_top = [14.0, 24.0, 36.0, 22.0, 22.0, 22.0, 22.0]
    _table_row(
        pdf,
        ["ID", "Provider", "Model", "Reported", "Est.", "Disc%", "$"],
        w_top,
        bold=True,
    )
    for c in bundle.top_calls:
        _table_row(
            pdf,
            [
                str(c.call_id),
                c.provider[:10],
                c.model[:14],
                str(c.reported_reasoning_tokens),
                str(c.combined_estimated_tokens),
                f"{c.discrepancy_pct:+.1f}",
                f"{c.dollar_impact:.3f}",
            ],
            w_top,
        )
    if not bundle.top_calls:
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 6, "No estimation rows in range (nothing to rank).", ln=1)
    pdf.ln(2)


def _write_timeseries_section(pdf: FPDF, bundle: AuditReportBundle) -> None:
    png = _timeseries_chart_png(bundle)
    _section_heading(pdf, "Time series")
    if png:
        pdf.image(io.BytesIO(png), w=min(pdf.epw, 180))
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 9)
        caption = (
            "Chart: daily sums of reported vs estimated reasoning tokens for the report window."
        )
        pdf.multi_cell(0, 4, caption)
    else:
        pdf.set_font("Helvetica", "I", 9)
        msg = "Not enough daily buckets for a time series (need 2+ days with data)."
        pdf.cell(0, 6, msg, ln=1)


def _write_limitations_page(pdf: FPDF) -> None:
    _section_heading(pdf, "Data limitations")
    _paragraph(
        pdf,
        "Estimates are statistical and depend on model calibration, prompt coverage, and "
        "latency measurement quality. They are not legal or accounting advice. Provider "
        "invoices remain the contractual source of truth; Overage highlights potential gaps "
        "for operational review.",
    )
    _paragraph(
        pdf,
        "Figures assume pricing tables aligned with your contract; mismatched rates will skew "
        "dollar impact. Very low call counts per group are marked low confidence in the API but "
        "are not individually flagged in every table in this PDF.",
    )


def render_audit_pdf(bundle: AuditReportBundle) -> bytes:
    """Render a complete audit PDF (PRD Story 6) into bytes."""
    import fpdf as _fpdf

    pdf = _fpdf.FPDF()
    pdf.set_auto_page_break(auto=True, margin=14)
    pdf.alias_nb_pages()
    pdf.add_page()
    _write_cover(pdf, bundle)
    _write_executive_and_methodology(pdf, bundle)
    _write_provider_model_tables(pdf, bundle)
    _write_top_calls_section(pdf, bundle)
    _write_timeseries_section(pdf, bundle)
    pdf.add_page()
    _write_limitations_page(pdf)
    return bytes(pdf.output())
