"""initial_schema

Revision ID: c1305a9cb9e6
Revises:
Create Date: 2026-05-10 12:31:07.045099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1305a9cb9e6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "api_call_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("prompt_length_chars", sa.Integer(), nullable=False),
        sa.Column("answer_length_chars", sa.Integer(), nullable=False),
        sa.Column("reported_input_tokens", sa.Integer(), nullable=False),
        sa.Column("reported_output_tokens", sa.Integer(), nullable=False),
        sa.Column("reported_reasoning_tokens", sa.Integer(), nullable=False),
        sa.Column("total_latency_ms", sa.Float(), nullable=False),
        sa.Column("ttft_ms", sa.Float(), nullable=True),
        sa.Column("is_streaming", sa.Boolean(), nullable=False),
        sa.Column("raw_usage_json", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_call_logs", schema=None) as batch_op:
        batch_op.create_index("idx_call_logs_user_provider", ["user_id", "provider"], unique=False)
        batch_op.create_index(
            "idx_call_logs_user_timestamp", ["user_id", "timestamp"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_api_call_logs_model"), ["model"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_call_logs_provider"), ["provider"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_call_logs_timestamp"), ["timestamp"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_call_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_keys_key_hash"), ["key_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_api_keys_user_id"), ["user_id"], unique=False)

    op.create_table(
        "discrepancy_alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("call_count", sa.Integer(), nullable=False),
        sa.Column("aggregate_discrepancy_pct", sa.Float(), nullable=False),
        sa.Column("dollar_impact", sa.Float(), nullable=False),
        sa.Column("confidence_level", sa.String(length=20), nullable=False),
        sa.Column("threshold_pct", sa.Float(), nullable=False),
        sa.Column("alert_status", sa.String(length=20), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("discrepancy_alerts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_discrepancy_alerts_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "estimation_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("call_id", sa.Integer(), nullable=False),
        sa.Column("palace_estimated_tokens", sa.Integer(), nullable=False),
        sa.Column("palace_confidence_low", sa.Integer(), nullable=False),
        sa.Column("palace_confidence_high", sa.Integer(), nullable=False),
        sa.Column("palace_model_version", sa.String(length=50), nullable=False),
        sa.Column("timing_estimated_tokens", sa.Integer(), nullable=False),
        sa.Column("timing_tps_used", sa.Float(), nullable=False),
        sa.Column("timing_r_squared", sa.Float(), nullable=True),
        sa.Column("combined_estimated_tokens", sa.Integer(), nullable=False),
        sa.Column("discrepancy_pct", sa.Float(), nullable=False),
        sa.Column("dollar_impact", sa.Float(), nullable=False),
        sa.Column("signals_agree", sa.Boolean(), nullable=False),
        sa.Column("domain_classification", sa.String(length=100), nullable=True),
        sa.Column("estimated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["call_id"], ["api_call_logs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("call_id"),
    )
    with op.batch_alter_table("estimation_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_estimation_results_discrepancy_pct"), ["discrepancy_pct"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("estimation_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_estimation_results_discrepancy_pct"))

    op.drop_table("estimation_results")
    with op.batch_alter_table("discrepancy_alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_discrepancy_alerts_user_id"))

    op.drop_table("discrepancy_alerts")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_user_id"))
        batch_op.drop_index(batch_op.f("ix_api_keys_key_hash"))

    op.drop_table("api_keys")
    with op.batch_alter_table("api_call_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_call_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_api_call_logs_timestamp"))
        batch_op.drop_index(batch_op.f("ix_api_call_logs_provider"))
        batch_op.drop_index(batch_op.f("ix_api_call_logs_model"))
        batch_op.drop_index("idx_call_logs_user_timestamp")
        batch_op.drop_index("idx_call_logs_user_provider")

    op.drop_table("api_call_logs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
